# Aktiviere Drehregler (Encoder)
CONFIG_EC11=y

# RGB Untergrundbeleuchtung (Underglow) aktivieren
CONFIG_ZMK_RGB_UNDERGLOW=y

# ZMK Studio aktivieren (Online-Tool Support)
CONFIG_ZMK_STUDIO=y

# Bluetooth Sendeleistung erhöhen
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Stromsparmodus (Deep Sleep) nach 30 Min Inaktivität
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Name des Keyboards im Bluetooth-Menü
CONFIG_ZMK_KEYBOARD_NAME="Dumbpad RGB"
