# Encoder Support
CONFIG_EC11=y

# RGB Underglow / Per-Key Support
CONFIG_ZMK_RGB_UNDERGLOW=y

# Energiesparen (Optional, aber empfohlen für nice!nano)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
